# Generated by Django 2.1.13 on 2019-10-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmoteca_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.IntegerField(),
        ),
    ]
