# Generated by Django 2.2.6 on 2019-10-21 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmoteca_api', '0002_auto_20191020_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
